# YAML file listing config. parameters
debug: False

model:
  # name: 'deit_base_distilled_patch16_224'
  # name: 'swin_large_patch4_window7_224'
  # name: 'vit_large_patch16_224'
  # name: "eva02_large_patch14_clip_224"
  name: vit_large_patch14_clip_224.laion2b
  
train_params:
  batch_size: 32
  epochs: 3
  lr: 1.0E-4
  eta_min: 1.0E-6
  img_aug:
    horizontal_flip: 0.0
  unfreeze:
    apply: False
    unfreeze_start: 18 # set it to lower number when significantly more samples are included

datasets:
  train: './kaggle/diffusiondb_ds2_ds3_ds5_ds6-2000_Train_TRUN200_cos_sim_False95.csv'
  val: './kaggle/val_data.csv'
  sample:
    base_dir: './kaggle/input/stable-diffusion-image-to-prompts'
    csv_name: 'prompts.csv'

wandb:
  mode: 'disabled'  #['disabled', 'offline', 'online']
  project: StableDiffusion
  log_results: True
  interval_type: steps #[epochs, steps]
  interval_delta: 1 #[int describing numer of intervals]
